AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  OrchestratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: stormguard-demo
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      CodeUri: ./
      Timeout: 300
      MemorySize: 1024
      Environment:
        Variables:
          BEDROCK_REGION: us-east-1
          BEDROCK_MODEL: anthropic.claude-3-sonnet-20240229-v1:0
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - bedrock:InvokeModel
              - s3:GetObject
              - s3:ListBucket
            Resource: '*'

  FunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref OrchestratorFunction
      AuthType: NONE

  FunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref OrchestratorFunction
      Action: lambda:InvokeFunctionUrl
      Principal: '*'
      FunctionUrlAuthType: NONE

Outputs:
  DemoUrl:
    Description: "Live Demo URL"
    Value: !GetAtt FunctionUrl.FunctionUrl